#pragma once

const int ORIGINAL_WIDTH = 240;
const int ORIGINAL_HEIGHT = 240;
const int RESOLUTION_MULTIPLIER = 4;
const int PLAYER_HORIZONTAL_VELOCITY = 40;
const int PLAYER_VERTICAL_VELOCITY = 24;
const int WALKING_ANIMATION_MILLISECS = 50;
const int STAIRS_ANIMATION_MILLISECS = 100;