#pragma once

const int ORIGINAL_WIDTH = 240;
const int ORIGINAL_HEIGHT = 240;
const int RESOLUTION_MULTIPLIER = 4;
const int PLAYER_HORIZONTAL_VELOCITY = 48;
const int PLAYER_VERTICAL_VELOCITY = 32;
const int WALKING_ANIMATION_MILLISECS = 50;
const int ENEMY_WALKING_ANIMATION_MILLISECS = 100;
const int ENEMY_SQUASHED_ANIMATION_MILLISECS = 100;
const int ENEMY_STUNNED_ANIMATION_MILLISECS = 400;
const int STAIRS_ANIMATION_MILLISECS = 100;
const int INGREDIENT_FALL_VELOCITY = 75;
const int COOK_DIE_ANIMATION_MILLISECS = 200;
const int COOK_CELEBRATE_ANIMATION_MILLISECS = 300;
const int PEPPER_ANIMATION_MILLISECS = 100;
const int INITIAL_LIVES = 4;
const int MAX_LIVES = 25;
const int INITIAL_PEPPER = 5;
const float ENEMY_PLAYER_SPEED_PROPORTION = 0.75;