#pragma once
#include <vector>
#include "Receiver.h"

class Receiver;
enum Message { NULL_MESSAGE, EXIT, MOVE_LEFT, MOVE_RIGHT, MOVE_UP, MOVE_DOWN, MAIN_ACTION, SWITCH_NIGHT_MODE, RESET_GAME, LOAD_NEW_LEVEL,
	ON_FLOOR, ON_INGREDIENT_1, ON_INGREDIENT_2, ON_INGREDIENT_3, ON_INGREDIENT_4, INGREDIENT_ON_FLOOR, INGREDIENT_INGREDIENT_HIT,
	INTERSECT_LIMIT_LEFT, INTERSECT_LIMIT_RIGHT, INTERSECT_STAIRS, INTERSECT_UP_STAIRS, INTERSECT_DOWN_STAIRS,
	ENEMY_ATTACK, ENEMY_SQUASHED, ENEMY_PEPPERED, ENEMY_UNPEPPERED, PEPPER_THROWN,
	INGREDIENT_FLOOR_HIT, INGREDIENT_FINISHED, PLAYER_DIED, GAME_STARTED, GAME_VICTORY,
	COUNT };

class MessageDispatcher {
	std::vector<Receiver*>* receivers;

public:
	MessageDispatcher();
	
	void subscribe(Message message, Receiver* receiver);
	void send(Message message);
	void clear();

	~MessageDispatcher();
};

